package lexfront

import (
	"path/filepath"
	"strings"

	"github.com/LukasSelin/doppel/internal/syntax"
)

// generatedMarkers are the declarations a generator leaves behind. Go's own
// convention is the strictest of them; the rest are the ones common enough
// across ecosystems to be a convention rather than a guess.
//
// The rule stays convention-deep on purpose, exactly as gofront's does: a
// generator that leaves no marker is invisible here, and the alternative —
// guessing from paths or names — is the heuristic the tagger and retriever
// refuse everywhere else.
var generatedMarkers = []string{
	"Code generated",
	"@generated",
	"DO NOT EDIT",
	"AUTO-GENERATED",
	"autogenerated",
	"Generated by",
}

// generatedHeaderLines is how far into a file the marker is looked for. Every
// convention puts it in the preamble; scanning the whole file would match a
// string literal in the middle of ordinary code.
const generatedHeaderLines = 12

// Parse turns source into the neutral IR using nothing but a tokenizer and a
// block rule. It never returns an error: there is no parse to fail, and a
// file whose shape this frontend cannot recognise yields a File with no
// functions, which is the same thing as a file with none.
func Parse(sp Spec, path string, src []byte) (*syntax.File, error) {
	toks := lex(src, sp)
	spans := segment(toks, sp)

	f := &syntax.File{
		Path:      path,
		Package:   packageOf(path),
		Lang:      sp.Lang,
		Generated: isGenerated(src),
		Imports:   imports(toks, sp),
	}

	b := &builder{toks: toks, sp: sp}
	for _, s := range spans {
		fn := syntax.Func{
			Name:      s.name,
			Receiver:  s.receiver,
			StartLine: toks[s.declTok].line,
			Exported:  isExported(s.name),
			Body:      b.block(s.bodyStart, s.bodyEnd),
		}
		for _, p := range s.params {
			// No types without a grammar. The name is what def-use needs;
			// the empty type is why Fingerprint.Types is weaker here, and
			// saying so with an empty string is more honest than inventing
			// a rendering from the header text.
			fn.Params = append(fn.Params, syntax.Param{Name: p})
		}
		fn.StartOffset = toks[s.declTok].off
		fn.EndOffset = endOffset(toks, s.bodyEnd, len(src))
		fn.Source = clamp(src, fn.StartOffset, fn.EndOffset)
		fn.Callees = callees(toks, s.bodyStart, s.bodyEnd)
		f.Funcs = append(f.Funcs, fn)
	}
	return f, nil
}

func endOffset(toks []token, bodyEnd, srcLen int) int {
	if bodyEnd < len(toks) {
		t := toks[bodyEnd]
		return t.off + len(t.text)
	}
	return srcLen
}

func clamp(src []byte, start, end int) string {
	if start < 0 || start > len(src) {
		return ""
	}
	if end > len(src) {
		end = len(src)
	}
	if end < start {
		return ""
	}
	return string(src[start:end])
}

// packageOf is the habitat key for a language with no package clause: the
// containing directory, slash-separated. culture's habitat model treats the
// package as an opaque partition key, so a directory serves the same purpose
// — functions that live together are modelled together.
func packageOf(path string) string {
	dir := filepath.ToSlash(filepath.Dir(path))
	if dir == "." || dir == "/" {
		return ""
	}
	return filepath.Base(dir)
}

// isExported has no declaration to read, so it uses the one convention that
// spans languages: a leading underscore means private. Everything else is
// treated as visible, which is the common case in every language that has no
// export keyword at all.
func isExported(name string) bool {
	return name != "" && !strings.HasPrefix(name, "_")
}

func isGenerated(src []byte) bool {
	s := string(src)
	for i, line := 0, 0; i < len(s) && line < generatedHeaderLines; line++ {
		j := strings.IndexByte(s[i:], '\n')
		if j < 0 {
			j = len(s) - i
		}
		seg := s[i : i+j]
		for _, m := range generatedMarkers {
			if strings.Contains(seg, m) {
				return true
			}
		}
		i += j + 1
	}
	return false
}

// imports binds local names to module paths from import-like lines, which is
// what makes TagSignals.RefPath — and therefore the resolved call channel —
// work for a language with no import AST.
//
// The shapes handled are the ones that recur: `import x`, `import x as y`,
// `from m import a, b`, `import {a, b} from "m"`, `require("m")`,
// `use a::b::c`, `#include <m>`.
func imports(toks []token, sp Spec) []syntax.Import {
	if len(sp.ImportKeywords) == 0 {
		return nil
	}
	kw := map[string]bool{}
	for _, k := range sp.ImportKeywords {
		kw[k] = true
	}
	seen := map[string]string{}
	var order []string
	add := func(local, path string) {
		if local == "" || path == "" {
			return
		}
		if _, ok := seen[local]; ok {
			return
		}
		seen[local] = path
		order = append(order, local)
	}

	for i := 0; i < len(toks); i++ {
		t := toks[i]
		if t.kind != tokIdent || !kw[t.text] || !t.nlPrev {
			continue
		}
		end := lineEnd(toks, i)
		names, path := importParts(toks, i, end)
		if path == "" {
			continue
		}
		for _, n := range names {
			add(n, path)
		}
	}

	out := make([]syntax.Import, 0, len(order))
	for _, l := range order {
		out = append(out, syntax.Import{Local: l, Path: seen[l]})
	}
	return out
}

// importParts pulls the bound names and the module path out of one import
// line. The path is the string literal if there is one, else the dotted or
// ::-joined identifier run; the names are what an "as" renames to, the
// braced list, or the path's last segment.
func importParts(toks []token, from, to int) ([]string, string) {
	var path string
	var names []string
	var braced []string
	depth := 0
	lastIdent := ""
	aliasNext := false

	for j := from + 1; j < to; j++ {
		t := toks[j]
		switch t.kind {
		case tokString:
			if path == "" {
				path = t.val
			}
		case tokOpen:
			depth++
		case tokClose:
			depth--
		case tokIdent:
			switch t.text {
			case "as":
				aliasNext = true
				continue
			case "from", "import":
				// `from m import a, b`: the module seen so far is the path.
				if path == "" && lastIdent != "" {
					path = lastIdent
				}
				continue
			}
			if aliasNext {
				names = append(names, t.text)
				aliasNext = false
				continue
			}
			if depth > 0 {
				braced = append(braced, t.text)
				continue
			}
			lastIdent = t.text
			if path == "" {
				path = t.text
			}
		}
	}
	if path == "" {
		path = lastIdent
	}
	if len(names) == 0 {
		names = braced
	}
	if len(names) == 0 && lastIdent != "" {
		names = []string{lastSegment(lastIdent)}
	}
	if len(names) == 0 && path != "" {
		names = []string{lastSegment(path)}
	}
	return names, path
}

func lastSegment(p string) string {
	p = strings.TrimSuffix(p, "/")
	for _, sep := range []string{"::", "/", "."} {
		if i := strings.LastIndex(p, sep); i >= 0 {
			return p[i+len(sep):]
		}
	}
	return p
}

func lineEnd(toks []token, i int) int {
	for j := i + 1; j < len(toks); j++ {
		if toks[j].nlPrev || toks[j].kind == tokEOF {
			return j
		}
	}
	return len(toks)
}

// callees names every call in the body, keeping the receiver when it is a
// bare identifier. This mirrors gofront's own rule exactly, because the call
// graph resolver reads it and its resolution ladder is written in terms of
// "receiver.selector" and bare names.
func callees(toks []token, from, to int) []string {
	seen := map[string]struct{}{}
	for i := from; i < to; i++ {
		if toks[i].kind != tokIdent {
			continue
		}
		if i+1 >= to || toks[i+1].kind != tokOpen || toks[i+1].text != "(" {
			continue
		}
		// "if (x)" and "switch (v)" are statements, not calls. Without this
		// the call channel — which feeds retrieval, the call graph, roles
		// and the culture ecology — carries "if" as one of the most common
		// callees in every C-family language, where it is pure noise.
		if isStmtKeyword(toks[i].text) {
			continue
		}
		name := toks[i].text
		if i-2 >= from && toks[i-1].kind == tokOp &&
			(toks[i-1].text == "." || toks[i-1].text == "::") &&
			toks[i-2].kind == tokIdent {
			// Only a bare identifier receiver qualifies, same as gofront.
			if i-3 < from || toks[i-3].kind != tokOp || toks[i-3].text != "." {
				name = toks[i-2].text + "." + name
			}
		}
		seen[name] = struct{}{}
	}
	if len(seen) == 0 {
		return nil
	}
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sortStrings(out)
	return out
}
