package parser

import "testing"

// Generated detection follows Go's own convention (https://go.dev/s/generatedcode)
// via ast.IsGenerated: the marker line before the first non-comment text, and
// nothing else — not paths, not file names, not a marker buried mid-file.
func TestGeneratedDetection(t *testing.T) {
	gen := `// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agent.proto

package p

func Size() int { return 0 }
`
	units, err := ParseSource("agent.pb.go", []byte(gen))
	if err != nil || len(units) != 1 {
		t.Fatalf("parse: %v (%d units)", err, len(units))
	}
	if !units[0].Generated {
		t.Error("marker before package clause not detected as generated")
	}

	hand := `package p

// Code generated is mentioned here in prose, mid-file, which per the
// convention marks nothing.
func Size() int { return 0 }
`
	units, err = ParseSource("size.go", []byte(hand))
	if err != nil || len(units) != 1 {
		t.Fatalf("parse: %v (%d units)", err, len(units))
	}
	if units[0].Generated {
		t.Error("hand-written file flagged as generated")
	}
}
